name: Coverage

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  pest-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: xdebug
          tools: composer:v2

      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run Pest coverage
        run: XDEBUG_MODE=coverage ./vendor/bin/pest --coverage --min=85
